### PR TITLE
Adds support for larger iOS device tokens

### PR DESCRIPTION
**Pull request by ulhas**
Addresses issue #265 

- Changed charfield max_length from 64 to 200
- Changed APNSDeviceSerializer validation to check string length for 200
- Changes to README and comments

### CODE REVIEW

**Comment by jleclanche** [comment]
Please fixup all commits into one when you're done.

**Comment by jleclanche** [comment]
This will need a migration, by the way.

**Comment by ulhas** [comment]
By fixing up all commits into one you mean to delete this pull request and create just one commit ?

**Comment by ulhas** [comment]
Devs would any way have to migrate when apple makes this change.

**Comment by jleclanche** [comment]
you don't need to create a new PR, just force push to this one.

**Comment by ulhas** [comment]
cool.

**Comment by ulhas** [comment]
Doing it now.

**Comment by ulhas** [comment]
@jleclanche Done

**Comment by jleclanche** [comment]
You still need to add a migration. I'll try to land this this weekend so it's ready for the .1 release.

**Comment by ulhas** [comment]
Damn! Any tips on how to add migrations ?

**Comment by ulhas** [comment]
@jleclanche do i need to modify the 0001_initial.py ?

**Comment by jleclanche** [comment]
No, just create a new migration as you would with makemigrations.

**Comment by ulhas** [comment]
@jleclanche how about now?

**Comment by jleclanche** [comment]
Looks good. There's a typo `devuce` in one of your comments - I'll try merge it tomorrow.

**Comment by ulhas** [comment]
Fixed.

**Pull request merged**
