### PR TITLE
UniqueValidator on GCMDevice Serializer

### PR DESCRIPTION
**Pull request by matthewh**
Added UniqueValidator to the GCMDevice Serializer to work around some mysql database limitations. A bandaid for issues mentioned in #184 #197 #216. With tests.

### CODE REVIEW

**Comment by jleclanche** [comment]
I'm ok with this but can you please reword the commit message to follow the rules in CONTRIBUTING.md?

**Comment by matthewh** [comment]
@jleclanche, if you are still unsatisfied with the commit message will you please provide some guidance.

**Comment by jleclanche** [comment]
Nope, this is great, thank you. :)

**Comment by jleclanche** [comment]
@jamaalscarlett thoughts?

**Comment by jamaalscarlett** [comment]
It looks good to me.

**Comment by jamaalscarlett** [comment]
@matthewh could you please rebase and force push, after that this is good to merge

**Comment by matthewh** [comment]
All set @jamaalscarlett

**Pull request merged**
