### PR TITLE
Add retry logic to bulk APNS messages when Apple reports a failing ident...

### PR DESCRIPTION
**Pull request by gesinger**
...ifier

See https://github.com/jleclanche/django-push-notifications/pull/138 for background.

### CODE REVIEW

**Comment by jleclanche** [comment]
@gesinger Can you fix travis and rebase on top of master, please?

**Comment by pcompassion** [comment]
waiting for this!

**Comment by gesinger** [comment]
Sorry about the delay. Fixed the travis build and rebased on top of master.

**Comment by jleclanche** [comment]
Need people to test this and come back to me with it, as I can't test APNS currently.

**Comment by pcompassion** [comment]
how do we test this?

**Comment by jleclanche** [comment]
Install django-push-notifications manually with the following from your virtualenv: 
```shell
git clone https://github.com/jleclanche/django-push-notifications.git
cd django-push-notifications
git checkout -b gesinger-retry-logic-for-bulk-apns master
git pull https://github.com/gesinger/django-push-notifications.git retry-logic-for-bulk-apns
./setup.py build && ./setup.py install
```

**Comment by gio82** [comment]
Anyone already tested this?

**Comment by gio82** [comment]
I'm testing it. Actually it doesn't work exactly as it is.

Anyway, in my understanding, in this solution it waits for each `_apns_check_errors` to give response before proceed with the next `registration_id`.
This is not best solution for big numbers (Apple response time may vary from 0.1 to 0.8 s).

I'm looking if I'm able to create something async. I'm not an expert though.

**Comment by gesinger** [comment]
Maybe I did something wrong (definitely possible), but it should only perform _apns_check_errors on the last registration_id:

(line 224)
if identifier == len(registration_ids) - 1:
    try:
        _apns_check_errors(socket)

In Apple's documents it says that re-running through the list of registration_ids should be pretty quick, so resending all of the registration_ids after the failed one is not too costly in terms of time (even if multiple fail).

That said, an async version could be a little more efficient.

**Comment by jleclanche** [comment]
Closing, no longer relevant with pyapns2.

**Pull request closed without merging**
