### PR TITLE
admin fix, unable to modify device entry, getting error about Hex field

### PR DESCRIPTION
**Pull request by theromis**

### CODE REVIEW

**Comment by jamaalscarlett** [comment]
@theromis this fix is not valid.  The device_id field is not read-only and should not be read only in the django admin.

**Comment by theromis** [comment]
@jamaalscarlett In this case please tell me how I can edit GCM devices in admin, because when I'm saving device entry I'm getting error.

**Comment by jamaalscarlett** [comment]
@theromis  Which version are you using?  And what device_id value are you attempting to save?  A stacktrace would also be helpful.

**Comment by theromis** [comment]
my version is 1.5.0
capture

**Comment by jamaalscarlett** [comment]
@theromis what is the value you are trying to save?

**Comment by theromis** [comment]
`15294002812468627586`

**Comment by jamaalscarlett** [comment]
Unfortunately this is a known issue with the HexIntegerField.  There is an existing PR that should fix this: https://github.com/jleclanche/django-push-notifications/pull/386

**Comment by theromis** [comment]
Ah, in this case great, waiting for this PR approval.

**Pull request closed without merging**
