### PR TITLE
Add APN alert title support

### PR DESCRIPTION
**Pull request by alexole**
Add support of title key in push notification alert property
https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/TheNotificationPayload.html#//apple_ref/doc/uid/TP40008194-CH107-SW4

### CODE REVIEW

**Comment by alexole** [comment]
To be improved

**Comment by alexole** [comment]
Just a tiny change, could you merge it please?

**Comment by jleclanche** [comment]
Thanks!

**Comment by aaronn** [comment]
Where did this change go?

**Pull request merged**
