### PR TITLE
Delegate APNS calls to PyAPNs2.

### PR DESCRIPTION
**Pull request by kit-cat**
Related: https://github.com/jleclanche/django-push-notifications/issues/170 and https://github.com/jleclanche/django-push-notifications/issues/357.

Use PyAPNs2 for calls to APNS, and move to APNS2 protocol.
Also add more tests for APNS devices.

This needs https://github.com/Pr0Ger/PyAPNs2/pull/31 (to keep the thread-id feature), which is why the Travis build fails :(

### CODE REVIEW

**Comment by jleclanche** [comment]
Can you make the test an expected failure for now?

**Comment by jleclanche** [comment]
You're removing a lot of settings items. Are there not arguments you can pass to PyAPNS2?

**Comment by kit-cat** [comment]
@jleclanche : PyAPNS2 merged my PR and released a 0.2.1, so the test should be fixed now.

For the settings:
- APNS_PORT and APNS_HOST were replaced by APNS_USE_ALTERNATIVE_PORT and APNS_USE_SANDBOX; I can only pass those args to PyAPNS2
- Removed APNS_MAX_NOTIFICATION_SIZE, I'm letting APNS handle this (esp. as notification max size had changed since APNS2)
- Removed APNS_FEEDBACK_HOST and APNS_FEEDBACK_PORT as there are no calls to the feedback service in PyAPNS2 - responses are handled with instant feedback in APNS2 (see https://developer.apple.com/videos/play/wwdc2015/720/ - `Instead of polling periodically from APNS feedback from your provider, you can now instead get feedback in the response.`). With instant feedback we also don't need APNS_ERROR_TIMEOUT

**Comment by jleclanche** [comment]
Ok, sounds great.

> APNS_PORT and APNS_HOST were replaced by APNS_USE_ALTERNATIVE_PORT and APNS_USE_SANDBOX; I can only pass those args to PyAPNS2

Any chance we could see the return of an override in PyAPNS2? The ability to run mock services on custom hosts is super useful. I won't make it a blocker to land this but I hate removing functionality.

**Comment by kit-cat** [comment]
Hate removing functionality too - I will try making a PR to PyAPNS2 and let you know what its maintainer thinks.

**Comment by kit-cat** [comment]
Well, looks like it's a no from PyAPNS2. https://github.com/Pr0Ger/PyAPNs2/pull/33

**Comment by jleclanche** [comment]
Ok, I don't think it's worth worrying too much about this. I'm fine with this landing. Could you rebase please?

**Comment by jleclanche** [comment]
@kit-cat I invited you as a collaborator. You can land this PR once it's rebased and you're comfortable with it.

**Comment by matthewh** [comment]
@kit-cat If you get this PR merged I'll make the necessary changes to support PyAPNs with my PR for multi application support.

**Comment by kit-cat** [comment]
@jleclanche @matthewh Thank you. I hope to rebase and land this later in the day.

**Comment by kit-cat** [comment]
Landed. :tada:
I'll make a PR supporting https://github.com/Pr0Ger/PyAPNs2/pull/37 asap.

**Comment by matthewh** [comment]
Awesome! I'll fix my PR. I noticed prune_devices went away. Does PyANs2 handle that? I don't see how to prune stale devices now.

**Comment by kit-cat** [comment]
@matthewh The "APNS feedback service" that returns stale devices we used to make calls to in APNS was deprecated in APNS2 (see how it's removed from the docs at https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/APNSOverview.html#//apple_ref/doc/uid/TP40008194-CH8-SW1, but appears in "Legacy information"). Since it was what was called in `prune_devices`, I removed the command.

Now in APNS2, notifications have instant feedback. If you send a notification to an unregistered (stale) device, APNS will return an Unregistered error code. In this case, we then mark the device as inactive in django-push-notifications, for single and bulk notifications.

**Pull request closed without merging**
