### PR TITLE
Fix wns connecting

### PR DESCRIPTION
**Pull request by piotrjakimiak**
Additionaly replaced tabs with spaces

### CODE REVIEW

**Comment by jamaalscarlett** [comment]
Did this fix an existing issue?  Or was there some change to WNS that broke the existing implementation?

**Comment by piotrjakimiak** [comment]
I've fixed few problems:
- tabs instead of spaces in source code
- accessing dict elements `SETTINGS.WNS_ACCESS_URL` is invalid because `SETTINGS` is dict
- `bytes(data, "utf-8")` is invalid on Python 2

**Comment by jamaalscarlett** [comment]
@piotrjakimiak thanks for this, neither @jleclanche or I use WNS, so I'd like to get some more eyes on this before merging.

**Comment by AdamBolfik** [comment]
@jamaalscarlett unfortunately not, I no longer have access to a Windows phone or the project that used this app.

**Comment by jleclanche** [comment]
i will not accept PRs that change the style that is *specifically laid out* in `CONTRIBUTING.md`. Sorry.

The PR is unreviewable *and* unmergeable because of it.

**Comment by jamaalscarlett** [comment]
I read that wrong, I assumed he was converting spaces to tabs.

**Comment by jleclanche** [comment]
I landed a bunch of fixes which should get rid of the highlighted issues.

**Pull request closed without merging**
