### PR TITLE
Django Rest Framework Support

### PR DESCRIPTION
**Pull request by matthewh**
Almost 100% based on PR #102. One minor update to the DeviceMixin for DRF v3 support. Also restricts device access to only those uploaded by the user.

### CODE REVIEW

**Comment by jleclanche** [comment]
Please squash all these commits together.

**Comment by matthewh** [comment]
@jleclanche Will do. Sorry, I misread your comment. Do you just want to close this PR and I'll open another?

**Comment by jleclanche** [comment]
@matthewh no you can just squash and force push, this PR will be updated.

**Comment by matthewh** [comment]
Turns out I am no good at squashing... I'll get it fixed

**Comment by matthewh** [comment]
I squashed the commits - do you have any more feedback for me?

**Comment by jleclanche** [comment]
Looks good. Can you rebase on top of master please and I'll merge it unless somebody objects.

**Comment by chrisballinger** [comment]
@matthewh Thank you!

**Comment by chrisballinger** [comment]
@matthewh When testing this briefly I noticed that the `APNSDeviceAuthorizedViewSet` when viewed in the DRF API browser shows a list of **all** users in the HTML form for authenticated but non-privileged users. This means that you can register devices for people other than yourself.

**Comment by matthewh** [comment]
Thanks @chrisballinger. Did you notice any other issues?

**Comment by OnlyInAmerica** [comment]
@matthewh to clarify on @chrisballinger's issue : There is *not* an issue creating devices for other users (the `IsOwner` permission prevents this). The only issue is that the Django Rest Framework form *does* enumerate all Users in the Device Form it presents even though it will not respect that selection and will instead use the `request.user`.

To fix this I think you'd just have to exclude the `users` field in `GCMDeviceSerializer` and  `APNSDeviceSerializer`:

```python
# /push_notifications/api/rest_framework.py

# Serializers
class APNSDeviceSerializer(ModelSerializer):

    class Meta:
        model = APNSDevice
        exclude = ('user',)    # ADD

    def validate_registration_id(self, value):
        # iOS device tokens are 256-bit hexadecimal (64 characters)

        if HEX64_RE.match(value) is None:
            raise ValidationError("Registration ID (device token) is invalid")
        return value


class GCMDeviceSerializer(ModelSerializer):
    class Meta:
        model = GCMDevice
        exclude = ('user',)     # ADD
```

**Comment by matthewh** [comment]
@OnlyInAmerica I thought it would be bad form to point out that distinction since it's still a security issue to expose all of the users. It has been addressed though I took the slightly more verbose approach and declared the fields.

```
class DeviceSerializerMixin(ModelSerializer):
   class Meta:
       fields = ("name", "registration_id", "device_id", "active", "date_created",)
       read_only_fields = ("date_created",)
```

**Comment by matthewh** [comment]
@jleclanche I've incorporated the suggestions made here and rebased on master.

**Comment by jleclanche** [comment]
Thanks, giving it a last review.

**Comment by jleclanche** [comment]
Looks good overall. Please fix the mentioned nits, change the commit message to just `Implement Django REST Framework support`, rebase on master (again) and this can land.

**Comment by matthewh** [comment]
Awesome - will fix today.

**Comment by OnlyInAmerica** [comment]
@matthewh I think we need a Django Rest Framework Field corresponding to the `HexIntegerField` Django model field. Could you review this [proposed fix](https://github.com/matthewh/django-push-notifications/commit/dac2236e43147ebd2c6d10b44826877174a1c262)?

Without this change I can't seem to work with `GCMDevice`s, but perhaps I missed something... Wouldn't be the first time :)

Boring Details:

Currently DRF maps `HexIntegerField` model fields to DRF's `IntegerField`, and this seems to prevent DRF from rendering affected models.

+ DRF's Renderers present the `HexIntegerField` HTML widget as a number type so hex values cannot be conveniently entered
+ DRF cannot present the hex value returned from `HexIntegerField.to_python(...)` in `IntegerField.to_representation(..)` so DRF will crash when rendering a `GCMDevice`

**Comment by matthewh** [comment]
@OnlyInAmerica Your proposed fix looks reasonable. I'll incorporate it with @jleclanche's requests.

**Comment by OnlyInAmerica** [comment]
@matthewh I [missed one additional required function](https://github.com/OnlyInAmerica/django-push-notifications/commit/dc6660f3dda2dcce69a16f9e0c81291e3dfdab95) in `HexIntegerField`. The complete class would be:

```python

class HexIntegerField(IntegerField):
    '''
    Store an integer represented as a hex string of form "0x01"
    '''
    def to_internal_value(self, data):
        data = int(data, 16)
        return super(HexIntegerField, self).to_internal_value(data)

    def to_representation(self, value):
        return value

```

Thx for bearing with me

**Comment by matthewh** [comment]
Committed and building. I've pulled in everyone's suggestions. @OnlyInAmerica I don't have any way to test GCM so please try this version when you can and let me know.

**Comment by matthewh** [comment]
The current failure looks like a download issue while pip installing packages. How do I rerun the build without pushing new files?

**Comment by jamaalscarlett** [comment]
Login to Travis and click the refresh icon next to the last build.

**Comment by matthewh** [comment]
@jamaalscarlett I logged in but do not see a refresh icon. I'm guessing that is because I don't have the correct permissions on this project.

**Comment by jamaalscarlett** [comment]
You create a Travis account then link it to your fork.  When you restart the build from there, it will be reflected in the pull request.

**Comment by jamaalscarlett** [comment]
git commit --amend 
git push
should also kick off a new build

**Comment by OnlyInAmerica** [comment]
@matthewh made one more minor change (PR'd your repo) but I did test with real GCM credentials today and it all works swimmingly!

**Comment by matthewh** [comment]
@OnlyInAmerica Thank you for testing this with GCM.

**Comment by matthewh** [comment]
Another other issues with this @jleclanche?

**Comment by jleclanche** [comment]
I can greenlight it. Is it ready to land?

**Comment by matthewh** [comment]
Yes, I believe so. I've had no additional feedback.

**Comment by jleclanche** [comment]
Landed. Well done, thanks a lot to everybody involved!

**Comment by chrisballinger** [comment]
:beers: :tada: :+1:

**Comment by brianlittmann** [comment]
Closes #99.

**Pull request merged**
