### PR TITLE
Add possibility to use different badge values in bulk send

### PR DESCRIPTION
**Pull request by alexole**
It's very valuable to set a proper badge value for different users (for now only one value for all the pushes possible) even when sending messages in bulk, this is an example of usage:

APNSDevice.objects.filter(user_id__in=user_ids).send_message(
        text, 
        badge=lambda token: APNSDevice.objects.get(registration_id=token).user.get_badges()
)

### CODE REVIEW

**Comment by jleclanche** [comment]
Thank you, looks good. Can you add some documentation about it in the readme?

**Comment by alexole** [comment]
Sure, will add into README.

**Comment by alexole** [comment]
Is that ok?

**Comment by jleclanche** [comment]
Landed in 0f90e14.

**Pull request closed without merging**
