### PR TITLE
Toxify the project

### PR DESCRIPTION
**Pull request by ticosax**
Test against all supported python versions.

### CODE REVIEW

**Comment by jleclanche** [comment]
Looks good, but is there any reason I need this?

**Comment by ticosax** [comment]
At the moment only to test `locally` will all python versions.
If later you want to support several django versions, tox will become your best friend

**Comment by ticosax** [comment]
regarding `requirements.txt` and tox. It is not always a good idea to couple them.

Because in tox you iterate over different exact version of your dependencies, while in `requirements.txt` you normally soft pin the version like `Django>=1.8`

**Comment by jleclanche** [comment]
Fair enough.

**Comment by jleclanche** [comment]
Landed in cfd9ae0.

**Pull request closed without merging**
