### PR TITLE
Apns remove mandatory topic

### PR DESCRIPTION
**Pull request by kit-cat**
- Upgrade pyAPNS to 0.3.0, restoring optional topics,
- Make our APNS_TOPIC setting optional again,
- Edit the docs accordingly.

I'm sorry this took so long, life got in the way.

### CODE REVIEW

**Comment by shigmas** [comment]
Oh, nice! Looks like this pulls in the AuthKey changes. I have that partially integrated, but it got a bit messy...

**Comment by jleclanche** [comment]
GTM!

**Comment by kit-cat** [comment]
@shigmas Thanks! Do you have a branch/PR for the AuthKey changes?
@jleclanche Thanks! I'll merge this asap

**Comment by shigmas** [comment]
It wasn’t finished - let me figure out where I left it. The new conf stuff is a little more complex, so I wanted to make sure I was putting the new variables in the right places. Also, there’s some state, since it generates a token that’s good for an hour (by default, but configurable), but that’s pushed to the user to manage, which I think is the right way to do it.

**Comment by grokcode** [comment]
@kit-cat, @shigmas anything I can do to help here?

**Comment by shigmas** [comment]
@kit-cat - did something pop up?

**Comment by kit-cat** [comment]
Merged my APNS_TOPIC related commits; sorry this took so long :(
Closing this as I managed to screw up my rebase

**Pull request closed without merging**
