### PR TITLE
Enabled support for arbitrary user model

### PR DESCRIPTION
**Pull request by fsto**
This enables the use of custom models.

A user can define which model to use by setting the `PUSH_NOTIFICATIONS_SETTINGS` key `USER_MODEL` to a model on the format `appname.Model`. The default user model is `settings.AUTH_USER_MODEL` which is the current user model in the library.

The `admin.py`'s `search_fields` only contains the user model's `USERNAME_FIELD` if the user model actually has that field.

### CODE REVIEW

**Comment by jleclanche** [comment]
Could you fixup the second commit into the first one please?

**Comment by fsto** [comment]
@jleclanche of course, this is now fixed.

**Comment by jleclanche** [comment]
lgtm but can you explain how this is necessary? why can't we just use the user model from the setting?

**Comment by fsto** [comment]
@jleclanche ok! There are cases when you have multiple user models.

A current case for me is that I've integrated with another system which holds the users I want to send push notfications to. The users (via their mobile clients) communicate with one aggregating server which communicates with (1) an external server holding user data and (2) the django server which complements the external server with extra user data and push notification functionality. In this case it therefore makes sense to send push notifications to another user model than `AUTH_USER_MODEL`.

**Comment by jleclanche** [comment]
Ok. I'm not too happy with the solution but I think it's fine to expose that field anyway.

**Comment by jleclanche** [comment]
Remove the try block and I'll land it.

**Comment by fsto** [comment]
@jackfengji just tell me how you'd be happy with the solution.

**Comment by jleclanche** [comment]
I meant more in a general sense that I don't think the correct way to solve your issue is to change that. But I am fine with exposing that as a setting anyway, so might as well.

**Comment by fsto** [comment]
Fixed @jackfengji

**Comment by jleclanche** [comment]
Landed in 40cfe2b

**Comment by rromanchuk** [comment]
@jleclanche this is a nice edition, some people don't extend any form of the django user object but still wan't these relationships. Thx

**Pull request closed without merging**
