### PR TITLE
qs.send_message refactoring (values_list makes additional sql query)

### PR DESCRIPTION
**Pull request by azevakin**

### CODE REVIEW

**Comment by jleclanche** [comment]
Looks good. I'd appreciated if someone can test, I'm on holiday currently.

J. Leclanche

**Comment by jleclanche** [comment]
Landed in 67fe37e

**Comment by jleclanche** [comment]
@azevakin you might want to add the email you used in that commit to your github profile.

**Comment by azevakin** [comment]
@jleclanche i did it.

**Pull request closed without merging**
