### PR TITLE
Retrive registration_ids in single query

### PR DESCRIPTION
**Pull request by koutoftimer**
Iterating through devices is not efficient way to recieve it's
registration ids. It costs additional time on transfeting data,
etc.

### CODE REVIEW

**Comment by koutoftimer** [comment]
@jleclanche Hi, do you have another post with title "tox how to"? Any way, I'm gonna fix it soon, maybe in few days.

**Comment by jleclanche** [comment]
I'm not familiar with tox myself unfortunately - someone else PR'd it and it looked good.  Travis is failing for a different reason though.

**Comment by koutoftimer** [comment]
Ok, I found problem. It is about returned type of `values_list`. I'm figuring out why it is a problem.

**Comment by koutoftimer** [comment]
@jleclanche Check it out.

**Comment by jleclanche** [comment]
gtm, thank you

**Comment by jleclanche** [comment]
Can you fix the typo in `Retrieve` in the commit message, and rebase on top of current master? (`git fetch jleclanche/master && git rebase jleclanche/master`)

**Comment by koutoftimer** [comment]
@jleclanche Done.

**Pull request merged**
