### PR TITLE
APNS bulk retry on fail

### PR DESCRIPTION
**Pull request by gio82**
Still not the best solution but gets the job done.

### CODE REVIEW

**Comment by jleclanche** [comment]
I'm not a fan of it but I'll merge it if it gets tested and approved.

**Comment by gio82** [comment]
Honestly I don't like it either. 
Maybe the best solution, avoiding to reinvent the wheel, would be to use PyAPNs libraries.

**Comment by jleclanche** [comment]
That's a huge dependency as it depends on Twisted. I'm not willing to let that go in just for this.

**Comment by jleclanche** [comment]
@gio82 please squash your commits

**Comment by gio82** [comment]
I made major amendments on the way APNS and GCM return results when bulk send message.

In particular both of them returns as common pattern:

    {'failure': 0, 'success': 0, 'invalid_registration_ids': []}

This way it's known how many failures, successes and where the failures occur.
`invalid_registration_ids` may be use to set `active=False` or directly `delete()`

GCM returns an additional key that is `canonical_ids`.

**Comment by gio82** [comment]
Actually I'm still working on GCM error messages. I'll update this code soon

**Comment by singleton11** [comment]
I think resending depends from buisness logic of project, because there is can be more than 1000 devices, and we need to answer to following questions:
1. through how many devices we should check errors (we need at least one second for error checking). If we have one error checking per 100 devices, we need 10 seconds to sending these messages.
2. What timeout should be set.
There is should be developer pain, but not django-push-notification. But I can mistake

**Comment by jleclanche** [comment]
Closing this, no longer relevant with pyapns2

**Pull request closed without merging**
