### PR TITLE
add on_delete=models.CASCADE to device abstract model and migrations

### PR DESCRIPTION
**Pull request by hylje**
they will be required for django 2.0

bonus: migration to sync GCMDevice.cloud_message_type.choices with model code

### CODE REVIEW

**Comment by jleclanche** [comment]
lgtm. @jamaalscarlett your opinion?

**Comment by jamaalscarlett** [comment]
Looks good to me.  If you could squash the commits, I can go ahead and merge.  Thanks!

**Comment by hylje** [comment]
Ping @jamaalscarlett

**Comment by jamaalscarlett** [comment]
thanks!

**Pull request merged**
