### PR TITLE
Parse gcm server response and set device active = false if either NotRegistered or InvalidRegistration errors are returned.  All other errors will continue to throw NotificationError

### PR DESCRIPTION
**Pull request by jamaalscarlett**

### CODE REVIEW

**Comment by jleclanche** [comment]
Your logic is destructive and doesn't check for what kind of error happens. That means if you mistakenly send, for example, an invalid TTL you will be deleting all the IDs it was sent to.

**Comment by jamaalscarlett** [comment]
I am checking for the error message.  Only NotRegistered or InvalidRegistration are affected, and the device is de-activated, not deleted.

**Comment by jleclanche** [comment]
No? You're only checking in the tests...

**Comment by jamaalscarlett** [comment]
I don't understand the test is being run against gcm.py, that is where the checking logic resides.

**Comment by jamaalscarlett** [comment]
I will add tests for other error codes to verify.

**Comment by jamaalscarlett** [comment]
Added a test to raise GCMError

**Pull request merged**
