### PR TITLE
Multiple apns certificates

### PR DESCRIPTION
**Pull request by cristiano2lopes**
Initial work on #130.

Documentation and test for the added features were added.

### CODE REVIEW

**Comment by jleclanche** [comment]
I'll have to do a more in-depth review once I get home, however a quick heads up. I'm seeing a lot of code that checks for deprecated settings and such - I'd like to move instead to writing Django 1.7 system checks. See this page for reference:

https://docs.djangoproject.com/en/1.8/ref/checks/

Here's an example of how we use them in Pootle:

https://github.com/translate/pootle/blob/master/pootle/checks.py

**Comment by cristiano2lopes** [comment]
Will change the test files to /dev/null. 
Regarding the checks I'am not familiar yet with the most recent releases of django (in fact I had to bac port this to the 1.2 release for work) but I can look into it. There is for sure a better way to do that on 1.7 and 1.8.

**Comment by matthewh** [comment]
What else is needed before this can be merged?

**Comment by jleclanche** [comment]
@matthewh I'd like to see the checks changed, and then i can do another more thorough review

**Comment by matthewh** [comment]
@jleclanche I rewrote the inline deprecated setting checks using django system checks but I see one issue with this change that makes me lean towards leaving it as is. It presumes the developer will always have APNS configured but it should still be possible to just use GCM. Unless we just make all of the checks warnings... What do you think?

**Comment by jleclanche** [comment]
You can simply skip the checks if there's nothing in the `APNS` settings dict.

**Comment by jleclanche** [comment]
Superceded by #226

**Pull request closed without merging**
