### PR TITLE
Added check to prevent admin from throwing GCMError during a bulk test message.

### PR DESCRIPTION
**Pull request by jamaalscarlett**
The error is now caught and displayed in the user message area.

### CODE REVIEW

**Comment by jamaalscarlett** [comment]
Remove duplicate code.

**Comment by jamaalscarlett** [comment]
@jleclanche any other issues?

**Comment by jleclanche** [comment]
I can't really do a full review right now, poke me on skype tomorrow if you like.

**Comment by jleclanche** [comment]
gtm

**Comment by jamaalscarlett** [comment]
Merged.

**Pull request closed without merging**
