### PR TITLE
Allow device uniqueness to be configured via settings

### PR DESCRIPTION
**Pull request by matthewh**
This will allow application developers to determine the best approach for device
 uniqueness in their application.

* For backwards compatibility we keep the registration_id on APNSDevice unique.
* The check can be overriden with a callable or tuple via UNIQUE_DEVICE_CHECK.

Resolves: #216

### CODE REVIEW

**Comment by matthewh** [comment]
I thought the cleanest approach to supporting customizable device unique requirements was to overload the Device models [_get_unique_checks](https://github.com/django/django/blob/8346680e1ca4a8ddc8190baf3f5f944f6418d5cf/django/db/models/base.py#L944) to inject a custom unique_together constraint.

**Comment by jleclanche** [comment]
I think it's a very bad idea to implement a setting for this. Migrations and settings never play well together.

I think the real approach is to allow subclassing of the *Device classes. But this needs more discussion before we let it go in.

In any case, at this point I don't want to take in any other rework until 1.5 is releasable. I really want 1.5 to get released and then we can talk about landing stuff for 2.0.

**Comment by matthewh** [comment]
Django unique_together constraints are applied at the application, not database level. This solution neatly sidesteps any migration issues by avoiding Meta.unique_together (which would generate a migration) and applies the constraint only at runtime. Device subclassing is definitely workable too. 

Is the multi-application PR on the table for 1.5?

**Comment by jleclanche** [comment]
> Django unique_together constraints are applied at the application, not database level

Is that so? That doesn't sound right at all.

https://docs.djangoproject.com/en/1.10/ref/models/options/#unique-together

> This is a tuple of tuples that must be unique when considered together. It’s used in the Django admin and is enforced at the database level (i.e., the appropriate UNIQUE statements are included in the CREATE TABLE statement).

**Comment by jleclanche** [comment]
> Is the multi-application PR on the table for 1.5? Do you have a written roadmap for 1.5? I have this PR, the multiple-app PR, and a registry PR waiting in the wings.

For 1.5 I want @kit-cat's PR to land to move us to pyapns2, which should get us #170 and #313 (or close enough to it that we can squash them). I also want #366 to land. I think that's enough for it. Everything else is in the [2.0 milestone](https://github.com/jleclanche/django-push-notifications/issues?q=is%3Aopen+is%3Aissue+milestone%3A2.0).

I'm also not opposed to releasing a 1.6 in between 1.5 and 2.0 if we see that the backwards-incompatible changes are taking a long time to land.

**Comment by matthewh** [comment]
True, but Django does not rely on the database raising a constraint error. Django checks these constraints manually at the application level:

https://github.com/django/django/blob/8346680e1ca4a8ddc8190baf3f5f944f6418d5cf/django/db/models/base.py#L995

**Comment by matthewh** [comment]
Closing, does not meet package maintainer's requirements.

**Pull request closed without merging**
