### PR TITLE
Adding documentation for undocumented feature: 'sending messages to t…

### PR DESCRIPTION
**Pull request by AnderUstarroz**
Adding documentation for undocumented feature: 'sending messages to topics'

### CODE REVIEW

**Comment by jleclanche** [comment]
Can you link back to this please?

**Comment by jamaalscarlett** [comment]
Could you please flatten the commits.  Otherwise this is good to merge.

**Comment by jamaalscarlett** [comment]
@AnderUstarroz can you clean up the commit so we can get this merged in?

**Comment by jamaalscarlett** [comment]
Merged.

**Pull request closed without merging**
